name: Build & Publish Docker image

on: 
  release:
    types: [published]
  pull_request:
    branches: [main, master, develop]

jobs:
  build_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: maxage/ad-service:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    name: Pull & Run Image
    needs: build_image
    runs-on: self-hosted
    steps:
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
        
      - name: Run image
        run: docker run -d -p 8080:8080 -p 18080:18080 maxage/ad-service:${{ steps.meta.outputs.version }}
        if: ${{ github.event_name == 'release'  }}
