# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:
    name: build app
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}.o
      app_name_exe: app_${{ matrix.os }}.o
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Build
      run: |
          go mod tidy
          go build -v ./...
    
    - name: Lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: .

    - name: Test
      run: |
          go mod tidy
          go test  -v -race -coverpkg=./... ./...
    
    - name: Build Main
      run: |
          go mod tidy
          go build -o ${{ env.app_name }} cmd/main/main.go
    
          
    - name: Upload an Artefact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app_matrix
        path: ${{ env.app_name }}
        retention-days: 5
        
  upload:
    name: upload & notify
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artefacts
        uses: actions/download-artifact@v3
        with:
          name: app_matrix
          
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "app_*.o"
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
          name: "documentation.zip" # optional string
          overwrite: "true" # optional boolean
          
      - name: Make Directory Structure
        run: |
          mkdir -p w/x/y
          date +%s > w/x/y/z
      - name: Mirror Directory Structure
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: w/x/y/z
          folderId: ${{ secrets.folderId }}
          overwrite: "true"
          mirrorDirectoryStructure: "true"
          
      - name: Send message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: app_*.o
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
