# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:
    name: build app
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}.o
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Build
      run: |
          go mod tidy
          go build -v ./...
    
    - name: Lint
      continue-on-error: true
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: .

    - name: Test
      run: |
          go mod tidy
          go test  -v -race -coverpkg=./... ./...
    
    - name: Build Object Main
      if: ${{ matrix.os != "windows-latest"}}
      run: |
          go mod tidy
          go build -o ${{ env.app_name }} cmd/main/main.go
    
    - name: Build Executable Main
      if: ${{ matrix.os == "windows-latest"}}
      run: |
          go mod tidy
          go build -o ${{ env.app_name }}.exe cmd/main/main.go
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: app_matrix
        path: ${{ env.app_name }}
        retention-days: 5
